---
name: docker-description

on:
  push:
    branches:
      - master
    paths:
      - VERSION
      - README.md
      - .github/workflows/docker-description.yml

jobs:
  docker-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: micromata/dave
          short-description: 'Dave is a simple webdav server. Dave is an abbreviation for: Distributed Authoring and Versioning made easy.'
